name: Monitoring OJS Cron

on:
  schedule:
    - cron: '0 */2 * * *'  # setiap 2 jam

jobs:
  trigger-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pengecekan jurnal
        run: curl -s https://ojsmonitor.vercel.app/api/hasil > /dev/null
